apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "migrations-pg.name" . }}
    chart: {{ template "migrations-pg.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "migrations-pg.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migrations-pg
          image: {{ .Values.imageRegistry }}:{{ .Values.imageTag }}
          imagePullPolicy: Always
          command: ["/bin/sh","-c"]
          args: 
            - /pg-scripting/migrate-db-all.sh $(pgServer) \
              $(pgPort) \
              $(pgUser) \
              $(pgPassword) \
              $(FlywayEnvironment)
          env:
            - name: pgServer
              value: {{ .Values.pgServer | quote }}
            - name: pgPort
              value: {{ .Values.pgPort | quote }}
            - name: FlywayEnvironment
              value: {{ .Release.Namespace }}
            - name: pgPassword
              value: {{ .Values.pgPassword | quote }}
            - name: pgUser
              value: {{ .Values pgUser | quote}}