apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-migration-job
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: migrations-pg
    repoURL: https://github.com/OliverLeighC/AutoSync-Hook-Bug.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: imageTag
          value: staged-example-1
  syncPolicy:
    automated: {}
