apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: root-application
    repoURL: https://github.com/OliverLeighC/AutoSync-Hook-Bug.git
    targetRevision: main
  syncPolicy:
    automated: {}
